name: Deploy preview


on:
  pull_request:
    branches:
      - master
    types: [closed]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  remove:
  runs-on: ubuntu-20.04
  continue-on-error: true
  if: github.event.pull_request.merged == true
  steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{ env.PR_NUMBER }}
