name: Deploy preview

on:
  pull_request: null

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: Build
        run: npm i && npm run build
        env:
          VUEPRESS_BASE: ${{ format('{0}{1}/', '/gh-preview-deploy/', env.PR_NUMBER) }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: www-dist
          target-folder: ${{ env.PR_NUMBER }}
      - name: Publish env
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://kulkarni-kashyap.github.io/gh-preview-deploy/${{ env.PR_NUMBER }}/
